import { createHash } from 'crypto';
import { promises as fs } from 'fs';
import { join, normalize } from 'path';
import { Injectable } from '@nestjs/common';
import { StorageProvider } from './storage.contracts';

/**
 * Local filesystem storage provider (default). Zero-config and works without
 * any external object store. Files are written under the configured storage
 * root (default `./storage`, overridable via STORAGE_LOCAL_ROOT) and are never
 * served directly by the web server — they're streamed by an authenticated API
 * route so tenant permissions still apply.
 *
 * Content served via a short-lived signed token generated by the documents
 * service; the provider itself only reads bytes back from disk.
 */
@Injectable()
export class LocalStorageProvider implements StorageProvider {
  readonly id = 'local';
  private readonly root: string;

  constructor(root = process.env.STORAGE_LOCAL_ROOT ?? './storage') {
    this.root = normalize(root);
  }

  private safeKey(key: string): string {
    // Prevent path traversal. Keys are org-prefixed/{uuid}.{ext} by the caller.
    const normalized = normalize(key);
    if (normalized.startsWith('..')) throw new Error('Invalid storage key.');
    return normalized;
  }

  private fullPath(key: string): string {
    return join(this.root, this.safeKey(key));
  }

  async put(key: string, body: Buffer, _contentType: string): Promise<{ success: boolean; key: string }> {
    const path = this.fullPath(key);
    await fs.mkdir(join(path, '..'), { recursive: true });
    await fs.writeFile(path, body);
    return { success: true, key };
  }

  async getUrl(key: string, _expiresInSeconds = 3600): Promise<string> {
    // Local files are streamed via an authenticated, permission-gated API route
    // whose URL is computed by the documents service. Here we return a stable
    // local token derived from the key (not in the file path).
    const encodeStr = `${this.id}:${key}`;
    const token = createHash('sha256').update(encodeStr).digest('hex').slice(0, 32);
    return `/api/v1/documents/by-key/${token}?k=${encodeURIComponent(key)}`;
  }

  async list(prefix: string): Promise<string[]> {
    const dir = this.fullPath(prefix);
    const entries = await fs.readdir(dir, { withFileTypes: true }).catch(() => [] as never[]);
    return entries.map((e) => join(prefix, e.name));
  }

  async delete(key: string): Promise<void> {
    await fs.unlink(this.fullPath(key)).catch(() => undefined);
  }

  /** Read raw bytes (used by the authenticated download route). */
  async read(key: string): Promise<Buffer> {
    return fs.readFile(this.fullPath(key));
  }

  /** Returns the mime-type/bytes for a key if present. */
  async exists(key: string): Promise<boolean> {
    return fs.access(this.fullPath(key)).then(() => true).catch(() => false);
  }
}
